package com.mygame;

public enum CardType {
    MONEY,
    PROPERTY_STANDARD,
    PROPERTY_WILD_BICOLOR,
    PROPERTY_WILD_MULTICOLOR,
    RENT_BICOLOR,
    RENT_WILDCOLOR,
    ACTION,
    BUILDING
}

